# this config file contains all config fields with comments
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
# 1 control plane node and 1 workers
nodes:
# the control plane node config
- role: control-plane
# the one worker
- role: worker
