---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    app.cncf.io/sample-annotation: "annotation-for-cncf-simple-flux"
  labels:
    app.kubernetes.io/name: cncf-simple-flux
    app.kubernetes.io/environment: development
  name: cncf-simple-flux-hpa
  namespace: cnf-simple-flux-ns
spec:
  maxReplicas: 2
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cncf-simple-flux-deploy
  targetCPUUtilizationPercentage: 30
