apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: app-namespaces
  namespace: flux-system
spec:
  interval: 1m
  path: "./app-namespaces"
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  validation: client

